# Generated by Django 6.0.7 on 2026-09-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_country_menuitem_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mood', 'Mood'), ('craving', 'Craving'), ('looks', 'Looks'), ('hunger', 'Hunger'), ('experience', 'Experience')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=100)),
            ],
            options={
                'ordering': ['type', 'name'],
                'constraints': [models.UniqueConstraint(fields=('type', 'code'), name='unique_discovery_tag_type_code')],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='discovery_tags',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='menu.discoverytag'),
        ),
    ]
