# Generated by Django 6.0.7 on 2026-09-13 09:10

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=orders.models.Order.generate_order_number, editable=False, max_length=20, unique=True),
        ),
    ]
